# theme: minimal
title: Curriculum Vitae, Kevin W. Mullet 
author: Kevin W. Mullet
description: self-referential pages site
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
